declare module 'lucide-react' {
  import { FC, SVGAttributes } from 'react';
  interface LucideProps extends SVGAttributes<SVGElement> {
    size?: number | string;
    className?: string;
  }
  type LucideIcon = FC<LucideProps>;
  export const ArrowLeft: LucideIcon;
  export const ArrowRight: LucideIcon;
  export const AlertCircle: LucideIcon;
  export const Award: LucideIcon;
  export const BookOpen: LucideIcon;
  export const CheckCircle: LucideIcon;
  export const CheckCircle2: LucideIcon;
  export const Eye: LucideIcon;
  export const EyeOff: LucideIcon;
  export const FileText: LucideIcon;
  export const Calendar: LucideIcon;
  export const Edit3: LucideIcon;
  export const FolderOpen: LucideIcon;
  export const Headphones: LucideIcon;
  export const Home: LucideIcon;
  export const Key: LucideIcon;
  export const LayoutDashboard: LucideIcon;
  export const Library: LucideIcon;
  export const Lightbulb: LucideIcon;
  export const Loader2: LucideIcon;
  export const Mic: LucideIcon;
  export const MoreVertical: LucideIcon;
  export const Music: LucideIcon;
  export const Pause: LucideIcon;
  export const Play: LucideIcon;
  export const Plus: LucideIcon;
  export const Flame: LucideIcon;
  export const Clock: LucideIcon;
  export const Target: LucideIcon;
  export const TrendingUp: LucideIcon;
  export const AlertTriangle: LucideIcon;
  export const Repeat: LucideIcon;
  export const RotateCcw: LucideIcon;
  export const Search: LucideIcon;
  export const Settings: LucideIcon;
  export const Save: LucideIcon;
  export const Trash: LucideIcon;
  export const Trash2: LucideIcon;
  export const Upload: LucideIcon;
  export const Volume2: LucideIcon;
  export const Wand2: LucideIcon;
  export const X: LucideIcon;
  export const XCircle: LucideIcon;
  export const Trophy: LucideIcon;
  export const Star: LucideIcon;
  export const Zap: LucideIcon;
}
